//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeGocNho_63134417.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public string Email { get; set; }
        public bool Admin1 { get; set; }
        public string Ten { get; set; }
        public string Password { get; set; }
    }
}
